name: Deploy Electrohub Frontend to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.AWS_EC2_HOST }} << 'EOF'
            set -e

            APP_DIR="/var/www/frontend-server"
            REPO_URL="https://github.com/aquibk580/electrohub-frontend.git"

            # Clone or pull repo
            if [ ! -d "$APP_DIR" ]; then
              sudo mkdir -p /var/www
              cd /var/www
              sudo git clone $REPO_URL frontend-server
            else
              cd "$APP_DIR"
              sudo git reset --hard HEAD
              sudo git pull origin main
            fi

            # Permissions
            sudo chown -R $USER:$USER "$APP_DIR"
            sudo chmod -R 755 "$APP_DIR"

            # Install Node.js if needed
            if ! command -v node &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt install -y nodejs
            fi

            cd "$APP_DIR"

            # Install dependencies & build with increased memory
            npm install --unsafe-perm
            NODE_OPTIONS=--max_old_space_size=1024 npm run build

            # Setup nginx to serve dist folder
            if ! command -v nginx &> /dev/null; then
              sudo apt install -y nginx
            fi

            # Configure nginx
            sudo tee /etc/nginx/sites-available/frontend-server > /dev/null << CONF
          server {
              listen 80;
              server_name ${AWS_EC2_HOST};

              root /var/www/frontend-server/dist;
              index index.html;

              location / {
                  try_files \$uri \$uri/ /index.html;
              }
          }
          CONF

            sudo ln -sf /etc/nginx/sites-available/frontend-server /etc/nginx/sites-enabled/frontend-server
            sudo nginx -t
            sudo systemctl reload nginx || sudo systemctl restart nginx

            # Final permissions
            sudo chown -R $USER:$USER "$APP_DIR"
          EOF

      - name: Clean up
        run: rm -f private_key.pem
