name: Deploy Electruhub Frontend to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.AWS_EC2_HOST }} << 'EOF'
            set -e  # Exit immediately on error

            APP_DIR="/var/www/frontend-server"

            # Clone or pull repo
            if [ ! -d "$APP_DIR" ]; then
              sudo mkdir -p /var/www
              cd /var/www
              sudo git clone https://github.com/aquibk580/electrohub-frontend.git frontend-server
            else
              cd "$APP_DIR"
              sudo git reset --hard HEAD
              sudo git pull origin main
            fi

            # Set permissions
            sudo chown -R $USER:$USER "$APP_DIR"
            sudo chmod -R 755 "$APP_DIR"

            # Install Node.js if not already installed
            if ! command -v node &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt install -y nodejs
            fi

            # Go to app dir and install dependencies
            cd "$APP_DIR"
            npm install --unsafe-perm

            # Install TypeScript and ts-node globally
            sudo npm install -g typescript ts-node

            # Compile TypeScript (if needed)
            npx tsc || true  # Avoid breaking if no tsconfig or TS files

            # Fix permissions for dist
            [ -d "dist" ] && sudo chown -R $USER:$USER "$APP_DIR/dist"

            # Install and configure Nginx
            if ! command -v nginx &> /dev/null; then
              sudo apt install -y nginx
            fi

            # Write Nginx config
            sudo tee /etc/nginx/sites-available/frontend-server > /dev/null << CONF
              server {
                  listen 80;
                  server_name ${AWS_EC2_HOST};

                  location / {
                      proxy_pass http://localhost:5173;
                      proxy_set_header Host \$host;
                      proxy_set_header X-Real-IP \$remote_addr;
                      proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                  }
              }
              CONF

            # Enable site and restart nginx
            sudo ln -sf /etc/nginx/sites-available/frontend-server /etc/nginx/sites-enabled/
            sudo nginx -t
            sudo systemctl reload nginx || sudo systemctl restart nginx

            # Final permissions
            sudo chown -R $USER:$USER "$APP_DIR"
          EOF

      - name: Clean up
        run: rm -f private_key.pem